### ISSUE TITLE
Tree is getting closed intermittently when selecting the node dynamically by using the method setSelectedByPath.

### ISSUE THREAD

**Issue by ssahphenom** [alekseymakhankov/hyper-tree#11]
Tree is getting closed intermittently when selecting the node dynamically by using the method setSelectedByPath. Below is the code snippet that I am using.

 useEffect(() => {
            treeHandlers.trees.tree.handlers.setSelectedByPath( activeTab );
        }
      }, [activeTab])

I am showing some data based on the click on the tree node as a tab view as shown in screen shot. When I am switching the tab, the corresponding node in the tree should be selected. So when I am selecting the node by using method setSelectedByPath, tree is getting closed sometimes.

![image](https://user-images.githubusercontent.com/102465387/160408265-c8c9ab61-b094-486b-a74e-ffb9874aad57.png)

Again when selecting the same time.

![image](https://user-images.githubusercontent.com/102465387/160408450-f864277c-9608-4eca-b0c1-12f57851cb70.png)

**Comment by alekseymakhankov** [comment]
Fixed in 0.3.12
