### ISSUE TITLE
Expand/Collapse all tree

### ISSUE THREAD

**Issue by mykhailokonst** [alekseymakhankov/hyper-tree#27]
How to expand or collapsed whole Tree on some external button click?

**Comment by Edmondton** [comment]
I was wondering the same

**Comment by Edmondton** [comment]
@mykhailokonst - i was able to get it to work by doing this example:

```
const rootId = treeHandlers.trees[your-tree-id].instance.data[0].id
treeHandlers.trees[your-tree-id].handlers.setOpen(rootId)


```

**Comment by mykhailokonst** [comment]
Yeah, I found the same, thanks, @Edmondton. But it whould be great to have some props handler for that feature in Tree component
