### ISSUE TITLE
Traverse Breadth bug

### ISSUE THREAD

**Issue by dziadyk-m** [alekseymakhankov/hyper-tree#6]
There is a bug in Node.ts file. _traverseBreadth should invoke _traverseBreadth recursively but it invoke _traverseDeep instead. Because of that childrenCount has incorrect value and vertical lines are shorter or longer then them should be.

Fix:
change line 539 in Node.ts:
this._traverseDeep(node.children, callback, depth + 1) -> this._traverseBreadth(node.children, callback, depth + 1)

**Comment by alekseymakhankov** [comment]
Fixed in 0.3.12
