### ISSUE TITLE
setNodeChildren gives "TypeError: e.setParent is not a function"

### ISSUE THREAD

**Issue by sohaib-khan** [alekseymakhankov/hyper-tree#7]
I am trying to dynamically add children in handleOnClick function by calling node.setNodeChildren and am getting e.setParent is not a function.

```
 <div onClick= { () => handleOnClick(node) }
          className={classnames({
            'tree-icon': true,
            'empty-icon': !node.hasChildren(),
            [node.options.opened
              ? 'close-icon'
              : 'open-icon']: isFolder(node.data.objectExtension) //,
          })}
      />
```

```
const handleOnClick = ( node ) => {
    let childData = [{
      objectName: 'Child 1',
    }]
    node.setNodeChildren(childData)
  }
```

**Comment by siddharthsathe** [comment]
Hey, did you find a solution to this?

**Comment by alekseymakhankov** [comment]
Hi, please try treeHandlers

`treeHandlers.trees[your-tree-id].handlers.setChildren(nodeId, children)` or `setRawChildren`, check the spec https://github.com/alekseymakhankov/hyper-tree#the-gsm-structure
And actually try setRawChildren if you want to pass only custom data to the children
