### ISSUE TITLE
Vertical lines incorrect size

### ISSUE THREAD

**Issue by ivanksh** [alekseymakhankov/hyper-tree#8]
There is problem with displaying vertical lines (see attachments bottom nodes lines) when opening nodes in high depth level.

It seems that it is related to the bug described in https://github.com/alekseymakhankov/hyper-tree/issues/6 because If I make suggested there changes everything works fine and the issue disappears.

![Screenshot from 2021-12-10 09-19-36-edited](https://user-images.githubusercontent.com/95905841/145539648-46b5cdb3-ee20-45db-adef-1640acfb68e8.png)

![Screenshot from 2021-12-10 09-26-21-edited](https://user-images.githubusercontent.com/95905841/145539667-e7125f72-2d9b-4cbf-9f48-5f8cb8d3efe1.png)

**Comment by alekseymakhankov** [comment]
Fixed in 0.3.12
